cache:
  directories:
    - $HOME/.composer/cache

language: php

sudo: false

dist: trusty

matrix:
  include:
    - php: 7.0
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.2
      env: LARAVEL='5.5.* 'TESTBENCH='3.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*' 'TESTBENCH='3.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*' 'TESTBENCH='3.7.*'
    - php: 7.3
      env: LARAVEL='5.6.*' 'TESTBENCH='3.6.*'
    - php: 7.3
      env: LARAVEL='5.7.*' 'TESTBENCH='3.7.*'
  fast_finish: true

before_script:
    - composer config discard-changes true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
  - vendor/bin/phpinsights --min-quality=80 --min-complexity=80 --disable-security-check -n -v
